Ju partner
odoo-cae/odoo-addons-hr-incubator pull request #11
Opened 2020-01-29 16:40 UTC by djulien19

Hey,
J'ai créé un champ initiate_date dans la fiche partenaire pour noter à quel moment ils font une session : information collective.
Cela permet d'éviter d'avoir à créer un candidat à chaque fois pour suivre cette information.

A suivre : le schéma complet du processus d'entrée d'un coopérateur !

2020-01-31 18:21 UTC, robinkeunen requested changes
Bien joué pour ta première PR chez nous! J'ai fais quelque commentaires dans le code, il faudra aussi que tu regardes les erreurs que Travis a généré.

Cependant, je pense que tu vas un peu trop vite: nous allons très certainement créer un module spécifique pour le parcours d'intégration. C'est là que devra s'intégrer ce champs. Donc je te recommande de mettre la PR en pause et de la reprendre lors du prochain sprint.

2020-01-31 18:21 UTC, robinkeunen commented on coopaname_custom/models/res_partner.py
> +# -*- coding: utf-8 -*-
pas nécessaire en python3

2020-01-31 18:21 UTC, robinkeunen commented on coopaname_custom/models/res_partner.py
> +from odoo import models, fields, api
`api` n'est pas utilisé

2020-01-31 18:21 UTC, robinkeunen commented on coopaname_custom/models/res_partner.py
> +        help="A quel moment, la personne fut accueillie par une information collective"
Attention à la longueur des lignes de codes (<88 caractères)

2020-01-31 18:21 UTC, robinkeunen commented on coopaname_custom/views/partner.xml
> +            </xpath>
Il faut fermer tes balises :-)

2020-01-31 18:21 UTC, robinkeunen commented on coopaname_custom/models/res_partner.py
> +        help="A quel moment, la personne fut accueillie par une information collective"
Et interdiction d'utiliser du français ;-)

2020-07-01 09:05 UTC, djulien19 commented on coopaname_custom/models/res_partner.py
> +# -*- coding: utf-8 -*-
Merci pour tes retours @robinkeunen 
Je ferme cette MR qui n'est plus nécessaire :)

2020-07-01 09:05 UTC, closed without merging